dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      # can't use mpl from system, need mpl 2.0 for MPLBACKEND to work
      # correctly
      - python-numpy
      - python3-numpy
      - python-scipy
      - python3-scipy

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd test && MPLBACKEND=Agg pytest --cov quadpy

after_success:
  - bash <(curl -s https://codecov.io/bash)
